/**
 * Installs (or removes, with --uninstall) the weekly auto-pull on macOS: `npm run schedule:install`.
 * Writes a launchd agent that runs `analyze-releases.ts --new` every Monday 9am using this
 * machine's node binary and repo path, then loads it. Re-run after moving the repo or
 * switching Node versions.
 */
import fs from 'fs';
import os from 'os';
import path from 'path';
import { execSync } from 'child_process';

const LABEL = 'com.hitpay.edm-weekly-pull';
const PLIST = path.join(os.homedir(), 'Library/LaunchAgents', `${LABEL}.plist`);
const LOG = path.join(os.homedir(), 'Library/Logs/hitpay-edm-weekly-pull.log');
const ROOT = fs.realpathSync(path.join(__dirname, '..'));
const NODE = process.execPath;
const domain = `gui/${os.userInfo().uid}`;

function unload() {
  try { execSync(`launchctl bootout ${domain}/${LABEL}`, { stdio: 'ignore' }); } catch { /* not loaded */ }
}

if (process.platform !== 'darwin') {
  console.log('The weekly auto-pull uses macOS launchd. On other systems, schedule `npm run analyze:new` with cron/Task Scheduler instead.');
  process.exit(0);
}

if (process.argv.includes('--uninstall')) {
  unload();
  if (fs.existsSync(PLIST)) fs.unlinkSync(PLIST);
  console.log('Weekly auto-pull removed.');
  process.exit(0);
}

const esc = (s: string) => s.replace(/&/g, '&amp;').replace(/</g, '&lt;');
const plist = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <!-- Generated by \`npm run schedule:install\` — weekly pull of new hitpay-core releases into data/edm.db. -->
  <key>Label</key><string>${LABEL}</string>
  <key>ProgramArguments</key>
  <array>
    <string>${esc(NODE)}</string>
    <string>${esc(path.join(ROOT, 'node_modules/ts-node/dist/bin.js'))}</string>
    <string>src/analyze-releases.ts</string>
    <string>--new</string>
  </array>
  <key>WorkingDirectory</key><string>${esc(ROOT)}</string>
  <key>StartCalendarInterval</key>
  <dict><key>Weekday</key><integer>1</integer><key>Hour</key><integer>9</integer><key>Minute</key><integer>0</integer></dict>
  <key>StandardOutPath</key><string>${esc(LOG)}</string>
  <key>StandardErrorPath</key><string>${esc(LOG)}</string>
</dict>
</plist>
`;

fs.mkdirSync(path.dirname(PLIST), { recursive: true });
fs.writeFileSync(PLIST, plist);
unload();
execSync(`launchctl bootstrap ${domain} "${PLIST}"`);

console.log(`Weekly auto-pull installed: every Monday 9am (runs on wake if the Mac was asleep).
Log: ${LOG}
Test it now: launchctl kickstart ${domain}/${LABEL}   then check the log.`);

const protectedDir = ['Documents', 'Desktop', 'Downloads'].find(d => ROOT.startsWith(path.join(os.homedir(), d) + path.sep));
if (protectedDir) {
  console.log(`
⚠️  This repo is inside ~/${protectedDir}, which macOS blocks background jobs from reading.
   Grant Full Disk Access to node once, or the job fails with "Operation not permitted":
   System Settings → Privacy & Security → Full Disk Access → + → ⌘⇧G → paste:
   ${NODE}`);
}
